development:
  adapter: postgresql
  database: fermedavenir_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fermedavenir_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fermedavenir_production
  pool: 5
  timeout: 5000